# Generated by Django 5.2.8 on 2025-12-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(db_index=True, help_text='Registration/plate number as it appears on the vehicle.', max_length=32)),
                ('vin', models.CharField(blank=True, db_index=True, help_text='Vehicle Identification Number (if available).', max_length=64, null=True)),
                ('engine_number', models.CharField(blank=True, db_index=True, help_text='Engine number (if available).', max_length=64, null=True)),
                ('make', models.CharField(help_text='Manufacturer, e.g., Toyota, Hyundai.', max_length=64)),
                ('model', models.CharField(help_text='Model name, e.g., Corolla, Elantra.', max_length=64)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Manufacturing year, if known.', null=True)),
                ('color', models.CharField(blank=True, help_text='Primary color, e.g., White, Black, Blue.', max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plate_number'], name='vehicles_ve_plate_n_a3accc_idx'), models.Index(fields=['vin'], name='vehicles_ve_vin_d8dea1_idx'), models.Index(fields=['engine_number'], name='vehicles_ve_engine__c969a4_idx')],
                'unique_together': {('plate_number', 'vin', 'engine_number')},
            },
        ),
    ]
