# Generated by Django 5.2.8 on 2026-05-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vin_required_plate_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='uniq_vehicle_engine_number_ci',
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='uniq_vehicle_vin_ci',
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='vehicle_vin_not_blank',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_ve_plate_n_a3accc_idx',
        ),
    ]
