# Generated by Django 5.2.8 on 2025-12-04 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('POLICE_EXTRACT', 'Police Extract'), ('VEHICLE_PHOTO', 'Vehicle Photo')], help_text='Type of document (e.g. Police Extract, Vehicle Photo).', max_length=32)),
                ('file', models.FileField(help_text='Reference to the file in storage.', upload_to='case_documents/')),
                ('original_filename', models.CharField(blank=True, help_text='Original filename as uploaded by the user.', max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the file (e.g. application/pdf, image/jpeg).', max_length=128, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes.', null=True)),
                ('sha256_hash', models.CharField(blank=True, help_text='SHA-256 hash of the file content for integrity/duplicate detection.', max_length=64, null=True)),
                ('is_private', models.BooleanField(default=True, help_text='If true, file should never be directly exposed publicly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(help_text='Case this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doc_type'], name='documents_d_doc_typ_4a1a00_idx')],
            },
        ),
    ]
