services:
  backend:
    build:
      context: ..
      dockerfile: infrastructure/docker/backend.Dockerfile
    environment:
      DEBUG: "False"
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    volumes:
      - backend_media:/app/media
    expose:
      - "8000"

  frontend:
    build:
      context: ..
      dockerfile: infrastructure/docker/frontend.Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    expose:
      - "3000"
    depends_on:
      - backend

  nginx:
    build:
      context: ..
      dockerfile: infrastructure/docker/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  backend_media:
