# Generated by Django 5.2.8 on 2025-12-03 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED_STOLEN', 'Verified Stolen'), ('REJECTED', 'Rejected'), ('RECOVERED', 'Recovered')], db_index=True, default='PENDING', max_length=32)),
                ('police_station', models.CharField(help_text='Name of the police station handling the case.', max_length=255)),
                ('police_case_number', models.CharField(help_text='Official police case reference number.', max_length=128)),
                ('incident_date', models.DateField(help_text='Date when the vehicle was stolen or went missing.')),
                ('last_seen_location_text', models.CharField(blank=True, help_text='Description of last seen location (address, area, etc.).', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the incident.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(help_text='User who submitted this stolen/missing report.', on_delete=django.db.models.deletion.CASCADE, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(help_text='The vehicle involved in this case.', on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'), models.Index(fields=['police_case_number'], name='cases_case_police__6257f1_idx')],
            },
        ),
    ]
