# Generated by Django 5.2.8 on 2026-03-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='allow_public_contact',
            field=models.BooleanField(default=False, help_text="If enabled, owner's phone may be shared after a valid vehicle sighting report."),
        ),
    ]
