# Generated by Django 5.2.8 on 2026-03-22 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_allow_public_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, max_length=255)),
                ('reporter_phone', models.CharField(blank=True, max_length=50)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('contact_revealed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
