# Generated by Django 5.2.8 on 2026-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_sightingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightingreport',
            name='contact_revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sightingreport',
            index=models.Index(fields=['case', 'created_at'], name='cases_sight_case_id_8c3cf2_idx'),
        ),
    ]
