# Generated by Django 5.2.8 on 2026-04-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_sightingreport_contact_revealed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='recovery_additional_notes',
            field=models.TextField(blank=True, help_text='Any other relevant recovery details provided by the owner.', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='recovery_circumstances',
            field=models.TextField(blank=True, help_text='How the vehicle was recovered and the circumstances around it.', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='recovery_date',
            field=models.DateField(blank=True, help_text='Date the vehicle was recovered.', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='recovery_location',
            field=models.CharField(blank=True, help_text='Where the vehicle was recovered.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='recovery_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the owner submitted a recovered-vehicle request.', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='recovery_vehicle_condition',
            field=models.TextField(blank=True, help_text='The condition/state of the vehicle when it was found.', null=True),
        ),
    ]
