# Generated by Django 5.2.8 on 2026-04-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_recovery_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='recovery_rejected_at',
            field=models.DateTimeField(blank=True, help_text='When the recovery request was rejected by a moderator/admin.', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='recovery_rejection_note',
            field=models.TextField(blank=True, help_text='Reason provided by moderator/admin when rejecting a recovery request.', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='recovery_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the recovery request was reviewed by a moderator/admin.', null=True),
        ),
    ]
