# Generated by Codex on 2026-05-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0006_case_recovery_rejected_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("NEEDS_INFO", "More Info Requested"),
                    ("VERIFIED_STOLEN", "Verified Stolen"),
                    ("REJECTED", "Rejected"),
                    ("RECOVERED", "Recovered"),
                ],
                db_index=True,
                default="PENDING",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the last moderation decision was made.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Last moderator/admin who made a moderation decision.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="moderator_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes visible to moderators/admins only.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="more_info_request_note",
            field=models.TextField(
                blank=True,
                help_text="Message explaining what additional information is needed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="more_info_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a moderator/admin requested additional information.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason provided by moderator/admin when rejecting the case.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="suspicious_flag",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this case has been flagged as suspicious/fraudulent.",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="suspicious_flag_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason this case was flagged as suspicious/fraudulent.",
                null=True,
            ),
        ),
    ]
