# Generated by Django 5.2.8 on 2026-05-10 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_moderation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the incident.', null=True, validators=[django.core.validators.MaxLengthValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='case',
            name='moderator_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible to moderators/admins only.', null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='case',
            name='more_info_request_note',
            field=models.TextField(blank=True, help_text='Message explaining what additional information is needed.', null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='case',
            name='recovery_additional_notes',
            field=models.TextField(blank=True, help_text='Any other relevant recovery details provided by the owner.', null=True, validators=[django.core.validators.MaxLengthValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='case',
            name='recovery_circumstances',
            field=models.TextField(blank=True, help_text='How the vehicle was recovered and the circumstances around it.', null=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='case',
            name='recovery_rejection_note',
            field=models.TextField(blank=True, help_text='Reason provided by moderator/admin when rejecting a recovery request.', null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='case',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided by moderator/admin when rejecting the case.', null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='case',
            name='suspicious_flag_reason',
            field=models.TextField(blank=True, help_text='Reason this case was flagged as suspicious/fraudulent.', null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='sightingreport',
            name='message',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
