# Generated by Django 5.2.8 on 2026-05-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_case_description_alter_case_moderator_notes_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sightingreport',
            index=models.Index(fields=['created_at'], name='cases_sight_created_dc5838_idx'),
        ),
        migrations.AddIndex(
            model_name='sightingreport',
            index=models.Index(fields=['contact_revealed'], name='cases_sight_contact_43472d_idx'),
        ),
    ]
