# Generated by Django 5.2.8 on 2026-05-10 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_sightingreport_cases_sight_created_dc5838_idx_and_more'),
        ('vehicles', '0006_alter_vehicle_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='case',
            name='cases_case_status_5f99d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_case_police__6257f1_idx',
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'created_at'], name='cases_case_status_3a818e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['suspicious_flag', 'created_at'], name='cases_case_suspici_cff827_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['moderated_at'], name='cases_case_moderat_85a5bc_idx'),
        ),
    ]
