# Generated by Django 5.2.8 on 2025-12-07 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE_VEHICLE', 'Create Vehicle'), ('UPDATE_VEHICLE', 'Update Vehicle'), ('DELETE_VEHICLE', 'Delete Vehicle'), ('CREATE_CASE', 'Create Case'), ('UPDATE_CASE', 'Update Case'), ('CHANGE_CASE_STATUS', 'Change Case Status'), ('UPLOAD_DOCUMENT', 'Upload Document')], help_text='High-level type of action.', max_length=64)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of what happened.')),
                ('target_app_label', models.CharField(blank=True, help_text='Django app label of the target object.', max_length=100)),
                ('target_model', models.CharField(blank=True, help_text='Model name of the target object.', max_length=100)),
                ('target_object_id', models.CharField(blank=True, help_text='Primary key of the target object as string.', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client (if available).', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string (if available).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
