# Generated by Django 5.2.8 on 2026-05-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE_VEHICLE', 'Create Vehicle'), ('UPDATE_VEHICLE', 'Update Vehicle'), ('DELETE_VEHICLE', 'Delete Vehicle'), ('CREATE_CASE', 'Create Case'), ('UPDATE_CASE', 'Update Case'), ('CHANGE_CASE_STATUS', 'Change Case Status'), ('UPLOAD_DOCUMENT', 'Upload Document'), ('DOWNLOAD_DOCUMENT', 'Download Document')], help_text='High-level type of action.', max_length=64),
        ),
    ]
