# Generated by Django 5.2.8 on 2026-05-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE_VEHICLE', 'Create Vehicle'), ('UPDATE_VEHICLE', 'Update Vehicle'), ('DELETE_VEHICLE', 'Delete Vehicle'), ('CREATE_CASE', 'Create Case'), ('UPDATE_CASE', 'Update Case'), ('CHANGE_CASE_STATUS', 'Change Case Status'), ('UPLOAD_DOCUMENT', 'Upload Document'), ('DOWNLOAD_DOCUMENT', 'Download Document'), ('REVEAL_CONTACT', 'Reveal Contact'), ('SUBMIT_SIGHTING', 'Submit Sighting'), ('REQUEST_RECOVERY', 'Request Recovery'), ('REJECT_RECOVERY', 'Reject Recovery'), ('FLAG_SUSPICIOUS', 'Flag Suspicious'), ('UPDATE_MODERATOR_NOTES', 'Update Moderator Notes'), ('REQUEST_MORE_INFO', 'Request More Info'), ('REJECT_CASE', 'Reject Case'), ('VERIFY_STOLEN', 'Verify Stolen'), ('MARK_RECOVERED', 'Mark Recovered'), ('PUBLIC_SEARCH', 'Public Search')], help_text='High-level type of action.', max_length=64),
        ),
    ]
